# Generated by Django 3.2.4 on 2021-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='longitude'),
        ),
    ]
